### ISSUE TITLE
Community maintainer

### ISSUE THREAD

**Issue by miles-w-3** [ansible-community/awx-operator-helm#15]
I would like to become a maintainer of this repo if possible. I worked on some of the initial logic for bootstrapping the kustomize manifests into the helm chart and allowing values kustomization. 

I know I discussed this helm chart configuration with @rooftopcellist and @TheRealHaoLiu a long time ago and I would like to see what can be done to improve it and make it more flexible

**Comment by oraNod** [comment]
Hey @miles-w-3 thanks for getting in touch! :raised_hands: We're happy to welcome you as a maintainer.

Someone else has asked about this too. [My response](https://github.com/ansible-community/awx-operator-helm/issues/6#issuecomment-2317738741) was that we want to do things in the spirit of FOSS meritocracy and start small then build up. I've set you up with triage access to get things started.

If you'd like to dip in and have a look at some of the issues we've added already, that'd be cool. It sounds like you've possibly got some ideas of your own, which is great. I'd encourage you to open some issues in the repo and break down your thoughts.

Also there's a forum post about versioning here: https://forum.ansible.com/t/awx-operator-helm-versioning/8228 - Your thoughts would be very welcome if you want to add anything to that discussion.

**Comment by oraNod** [comment]
@miles-w-3 Hi again. I've resent the invitation to join the repo with triage level access. The previous one expired. We'd love to have you as a maintainer so please do accept and let us hear from you. Cheers.

**Comment by miles-w-3** [comment]
Hi, sorry for the delay. Thank you for the invite!

**Comment by oraNod** [comment]
No worries @miles-w-3 welcome!
