### ISSUE TITLE
Add ability to specify labels for "default" AWX template

### ISSUE THREAD

**Issue by hagaram** [ansible-community/awx-operator-helm#16]
### Feature Summary

"migrated" from https://github.com/ansible/awx-operator/issues/1820

At the moment there is possibility to specify additional_labels for child objects of AWX object, which si neat, but if someone want to use this functionality with default helm awx template, there is no way to specify labels for the AWX object itself (https://github.com/ansible/awx-operator/blob/devel/.helm/starter/templates/awx-deploy.yaml).
Or at least I dont know how, so I've used kustomize to patch the object. This could be easily avoided.

If no labels are specified for AWX object, then additional_labels are not being applied.

Please add ability to specify labels, when using default AWX deploy template.

**Comment by oraNod** [comment]
Thanks for migrating the issue @hagaram
