### ISSUE TITLE
Specify private registry for images

### ISSUE THREAD

**Issue by mesenger** [ansible-community/awx-operator-helm#17]
Hi,
I would need to specify location for container images to be fetched from my private registry. I am able to do that for Operator itself inside template:
templates/deployment-awx-operator-controller-manager.yaml: image: quay.io/ansible/awx-operator:2.19.0

But how can I do the same for AWX deployment itself, for image: quay.io/ansible/awx-ee:latest ?

**Comment by schen1** [comment]
Hi @mesenger,

Thanks for reaching out.

In the values file, you could for example use`AWX.spec.image`. The same is true for the the Execution Environments with `AWX.spec.ee_images`.

The full reference of the CRD is available in the following [link](https://github.com/ansible/awx-operator/blob/devel/config/crd/bases/awx.ansible.com_awxs.yaml).

I hope that answers your question.

**Comment by oraNod** [comment]
Thanks for responding @schen1 I'll close this issue now. We can reopen if needed.

**Comment by naveen1583** [comment]
> Hi, I would need to specify location for container images to be fetched from my private registry. I am able to do that for Operator itself inside template: templates/deployment-awx-operator-controller-manager.yaml: image: quay.io/ansible/awx-operator:2.19.0
> 
> But how can I do the same for AWX deployment itself, for image: quay.io/ansible/awx-ee:latest ?

Were you able to figure out how to specify private registry paths for images?
