### ISSUE TITLE
awx-operator generates the password instead of the awx-admin-password secret

### ISSUE THREAD

**Issue by mateuszl0295** [ansible-community/awx-operator-helm#26]
Hello, I'm trying to install awx-ansible using helm chart on rancher-managed kubernetes. At this point, I tried a simple configuration with my own admin password. Unfortunately, the password generates itself every time. Where am I going wrong?

I tried these values.yaml combinations:

AWX:
  enabled: true
  name: awx
  customSecrets:
    enabled: true
    admin:
      enabled: true
      password: mypassword
      secretName: awx-admin-password
  spec:
    admin_user: admin
    admin_password_secret: awx-admin-password
    ipv6_disabled: true
    service_type: NodePort
    nodeport_port: 30180

OR

AWX:
  enabled: true
  name: awx
  spec:
    admin_user: admin
    admin_password_secret: awx-admin-password
    ipv6_disabled: true
    service_type: NodePort
    nodeport_port: 30180
  customSecrets:
    enabled: true
    admin:
      enabled: true
      password: mypassword
      secretName: awx-admin-password

OR

AWX:
  enabled: true
  name: awx
  customSecrets:
    enabled: true
    admin:
      enabled: true
      password: mypassword
      secretName: awx-admin-password
  spec:
    admin_user: admin
    ipv6_disabled: true
    service_type: NodePort
    nodeport_port: 30180

OR:

AWX:
  enabled: true
  name: awx
  spec:
    admin_user: admin
    admin_password_secret: awx-admin-password
    ipv6_disabled: true
    service_type: NodePort
    nodeport_port: 30180
  customSecrets:
    enabled: true
    admin:
      enabled: true
      password: mypassword
      secretName: awx-admin-password

**Comment by oraNod** [comment]
hey @mateuszl0295 I don't know the answer to that but @schen1 or @miles-w-3 might have a better idea. I'd also recommend asking over in the forum at: https://forum.ansible.com/c/help/6/none

there are lots more active users on the forum than there are in this repo so you're more likely to get a response there. best of luck!

**Comment by schen1** [comment]
Hey @mateuszl0295, please indent correctly the values file content so that we can reproduce/troubleshoot the issue on our end.

Thank you!

**Comment by YaronL16** [comment]
Hey @mateuszl0295, What you were trying to do is not possible. The password must be configured inside a secret before installing the operator. You can choose to use a custom secret like [this](https://ansible.readthedocs.io/projects/awx-operator/en/latest/user-guide/admin-user-account-configuration.html?h=admin#secret-key-configuration)

If you don't like the idea of creating the secret yourself, I suggest using something like External Secrets Operator to fetch the password from an external source (like Vault) and dynamically update the awx-admin-password for you.

The password can also be changed manually after creation, via the awx-web pod with the awx-manage binary

**Comment by oraNod** [comment]
Thanks for addressing this @YaronL16 I'll go ahead and close this issue. We can always reopen if @mateuszl0295 disagrees or has follow on questions.
