### ISSUE TITLE
No Helm Repo URL in README

### ISSUE THREAD

**Issue by howardjones** [ansible-community/awx-operator-helm#3]
Is there an actual helm repo for this chart?

The README points to the docs in the awx-operator repo, which tell you to add a (no longer existing) helm repo at https://ansible.github.io/awx-operator/

Is there a new community repo? The bare helm install suggestion in the README doesn't work without one.

**Comment by howardjones** [comment]
Weirdly, the gh-pages branch has a README which _does_ have this information!

helm repo add awx-operator https://ansible-community.github.io/awx-operator-helm/

**Comment by oraNod** [comment]
@howardjones Thanks for pointing this out and creating an issue. I think the outdated info in the README was just an oversight. I've sent a PR to correct if you'd like to take a quick look and comment.
