### ISSUE TITLE
Community maintainer

### ISSUE THREAD

**Issue by schen1** [ansible-community/awx-operator-helm#6]
Hi all,

As discussed in the community call,  I'd like to be a community contributor/maintainer of this new repository.

I'm experienced with ansible operators and the awx-operator, having used for the last 3-4 years.
Additionally, I have been using the downstream enterprise version at customers.

Thanks,
Sylvain

**Comment by oraNod** [comment]
Hi @schen1 Thanks for getting in touch! First of all, let me apologize for the delay in responding to you. I was away on holiday for a while. :beach_umbrella: 

You're very welcome to join as a maintainer. I've granted you access with triage permissions for now. In the spirit of FOSS meritocracy, how about we start with some issues and build up?

Let me put together some issues, you can also submit any of your own ideas, and we can get started. Does that sound agreeable?

**Comment by schen1** [comment]
Hi @oraNod, thanks a lot.

That sounds great! Looking forward to collaborating with you and the community
