### ISSUE TITLE
Helm chart lint fails in ci

### ISSUE THREAD

**Issue by oraNod** [ansible-community/awx-operator-helm#7]
The ci workflow is failing on the step to lint the helm chart:

```
Error: 1 chart(s) linted, 1 chart(s) failed
==> Linting ./charts/awx-operator
[ERROR] Chart.yaml: version is required
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: validation: chart.metadata.version is required
[ERROR] : unable to load chart
validation: chart.metadata.version is required
``` 

This occurs in the step to [build and lint the helm chart](https://github.com/ansible-community/awx-operator-helm/blob/7915d1e85019d20da3e965f820322ec11747c535/.github/workflows/ci.yaml#L41).

**Comment by oraNod** [comment]
Thanks for jumping on this @schen1

I'm a little uncertain about the versioning. The makefile in this repo includes the makefile from the awx-operator repo. So I think all we need to do is add tags.

It might be beneficial to keep the same version as the awx-operator for existing installations. I'm not familiar enough with the helm chart to know how disruptive it would be to go from version `2.19.1` to, say, version `1.0`. That might also be confusing, if you weren't able to easily tell which version of the chart matches the operator version. Although maybe that's not a big requirement.

An option might be to create a workflow that runs periodically and pushes any new tags from the awx-operator to this repo, basically mirroring the tags.

We could create a forum post and ask folks what they think. Would you be on for doing that @schen1 ?

**Comment by schen1** [comment]
@oraNod thanks for sharing your thoughts.

It's definitely better to brainstorm and collect ideas to move forward.

I started a [forum post](https://forum.ansible.com/t/awx-operator-helm-versioning/8228)

**Comment by oraNod** [comment]
thanks @schen1 that's great. I appreciate you adding some technical clarification around `appVersion` and `version`.

it might also be good to post that to the bullhorn newsletter for more reach. basically you ping  `@newsbot` followed by the details in the social channel in matrix. I can do that if you prefer.

looking forward to some collab on this helm chart! I'm excited. it's going to be fun and good learning.

btw, I seem to recall meeting you in person, either at DevConf or CfgMgmtCamp. did you hang out at the Ansible booth at one of those events?

**Comment by schen1** [comment]
Great, thanks @oraNod!

Regarding the bullhorn newsletter, if you could do it, that would be great. I'm not yet familiar with Matrix and all the fancy things that can be done!

Yes, we've indeed met for the first time at DevConf! Hopefully, it won't be the last time :)

Looking forward to contributing and seeing the development of AWX and of its operator

**Comment by oraNod** [comment]
@schen1 I've posted the forum link to the bullhorn newsletter. FYI you can read about how to post to the bullhorn here: https://forum.ansible.com/t/about-the-newsletter-category/166?extIdCarryOver=true&sc_cid=701f2000001Css5AAC

For Matrix, there's an FAQ here: https://hackmd.io/@ansible-community/community-matrix-faq

And you can find all the info you need about communication here: https://docs.ansible.com/ansible/devel/community/communication.html

Cheers!
